name: deploy

on:
  create:
    tags:
      - v*

env:
  APP_IMAGE_NAME: diabloboom/rss

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}
      - run: docker pull diabloboom/rss-caddy:latest
      - run: docker tag diabloboom/rss-caddy:latest diabloboom/rss-caddy:${{ github.ref_name }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - run: docker push diabloboom/rss-caddy:${{ github.ref_name }}
