name: release

on:
  create:
    tags:
      - v*

env:
  APP_IMAGE_NAME: diabloboom/rss

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Скачиваем образ
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest
      # Тегируем, тег в образе совпадает с тегом git-репозитория
      # github.ref_name - в данном случае имя тега
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Заливаем новый тег
      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}
